calismaodasi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('rooms/', include(('rooms.urls', 'rooms'), namespace='rooms')),
    path('reservations/', include(('reservations.urls', 'reservations'), namespace='reservations')),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
    path('account/', include('account.urls')),

]


reservations/urls.py
from django.urls import path
from . import views
app_name = 'reservations'

urlpatterns = [
    path('create/<int:room_pk>/', views.create_reservation, name='create'),
    path('mine/', views.my_reservations, name='mine'),

     path('update/<int:pk>/', views.update_reservation, name='update_reservation'),
    path('delete/<int:pk>/', views.delete_reservation, name='delete_reservation'),
]

rooms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.room_list, name='list'),
    path('<int:pk>/', views.room_detail, name='detail'),
]


rooms/models.py
from django.db import models
from django.utils.text import slugify

class Room(models.Model):
    name = models.CharField(max_length=100, verbose_name="Oda Adı")
    # Utilisation de blank=True pour éviter les erreurs lors de la création manuelle
    slug = models.SlugField(unique=True, blank=True, null=True)
    capacity = models.PositiveIntegerField(verbose_name="Kapasite")
    location = models.CharField(max_length=200, verbose_name="Konum", blank=True)
    is_active = models.BooleanField(default=True, verbose_name="Aktif mi?")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

rooms/views.py
from django.shortcuts import render
from .models import Room

# Create your views here.
def room_list(request):
    rooms = Room.objects.all()
    return render(request, 'list.html', {'rooms': rooms})

def room_detail(request, pk):
    room = Room.objects.get(pk=pk)
    return render(request, 'detail.html', {'room': room})


rooms/templates/detail.html
{% extends "base.html" %}
{% block title %}Oda Detayı{% endblock %}
{% block content %}
  <h2>{{ room.name }}</h2>
  <p><strong>Kapasite:</strong> {{ room.capacity }} kişi</p>
  <p><strong>Konum:</strong> {{ room.location }}</p>
{% endblock %}

rooms/templates/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Odalar{% endblock %}
{% block content %}
<div class="container py-5">
  <h2 class="mb-4 text-white fw-bold">Çalışma Odaları</h2>

  <div class="col-md-6 d-none d-md-block text-center hero-image-col">
            <img src="{% static 'img/elegant-vintage-library-with-wooden-shelves-sophisticated-green-lamps.jpg' %}" alt="Çalışma Odası" class="img-fluid hero-image">
        </div>

  <ul class="list-group custom-btn-2">
    {% for room in rooms %}
      <li class="list-group-item d-flex justify-content-between align-items-center blurred-box">
        <div>
          <h6 class="fw-bold mb-1">{{ room.name }}</h6>
          <small class="text-muted">{{ room.description|truncatewords:12 }}</small>
        </div>
        <div class="d-flex gap-3">
          <a href="{% url 'rooms:detail' room.id %}" class="custom-btn">Detay</a>
          <a href="{% url 'reservations:create' room.id %}" class="custom-btn">Rezervasyon </a>
        </div>
      </li>
    {% empty %}
      <li class="list-group-item text-muted">Şu anda hiç oda bulunmamaktadır.</li>
    {% endfor %}
  </ul>
</div>

{% endblock %}